h () {
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	s
	}
	s () {
		mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	mkdir $RANDOM$RANDOM$RANDOM$RANDOM
	h
	}
	s