echo "wait open many site"
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
ermux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
ermux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
termux-open https://google.com > /dev/null 2>&1
termux-open https://mbasic.facebook.com > /dev/null 2>&1
														